apply_requirements:
  checks:
  - approved:
      all_of:
      - user:terrateam-test-user02
      enabled: true
    tag_query: dir:tf1
  - approved:
      all_of:
      - user:terrateam-test-user01
      enabled: true
    tag_query: dir:tf2
engine:
  name: tofu
