dirs:
  tf:
    create_and_select_workspace: false
    tags:
    - tf
    when_modified:
      file_patterns:
      - ${DIR}/*.tf
      - ${DIR}/*.tfvars
      - ${DIR}/backend-${WORKSPACE}.conf
    workspaces:
      workspace1:
        tags:
        - workspace1
        when_modified: null
      workspace2:
        tags:
        - workspace2
engine:
  name: tofu
workflows:
- plan:
  - extra_args:
    - -backend-config=backend-workspace1.conf
    type: init
  - extra_args:
    - -var-file=workspace1.tfvars
    type: plan
  tag_query: tf workspace1
- plan:
  - extra_args:
    - -backend-config=backend-workspace2.conf
    type: init
  - extra_args:
    - -var-file=workspace2.tfvars
    type: plan
  tag_query: tf workspace2
