dirs:
  modules/**/*.tf:
    when_modified:
      file_patterns: []
  tf:
    when_modified:
      file_patterns:
      - tf/**.tf
      - modules/**
      - '!modules/ignore/*.tf'
engine:
  name: tofu
