stacks:
  names:
    tf1:
      tag_query: 'dir:tf1'
      rules:
        modified_by:
          - tf2
    tf2:
      tag_query: 'dir:tf2'
      rules:
        modified_by:
          - tf1

engine:
  name: tofu
